version: "3.0"
services:
  hello-weeve:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "hello-weeve"
      MODULE_TYPE: "Processing"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      EGRESS_URLS: "https://test-module.free.beeceptor.com"
      TEMPERATURE_LABEL: "temperature"
    ports:
      - 80:80
